### ISSUE TITLE
Hardware SID player

### ISSUE THREAD

**Issue by LouDnl** [r-moeritz/crsid-by-hermit#1]
Hi @r-moeritz , great project! 
I am looking for some information to implement cRSID as base / replacement for the SidBerry version I maintain.
I want to add hardware SID player support for USBSID, but am failing to see how IO writes to the SID emulation are handled in cRSID so I can hook into that.
Do you have the time to give me some pointers?
Thanks!

**Comment by LouDnl** [comment]
Okay, working on an adaption. Going to hook into the wr() and wr2() functions.

**Comment by LouDnl** [comment]
Any tips on a better place to hook in are much appreciated!

**Comment by r-moeritz** [comment]
Hi @LouDnl , sorry but this is not my code. If you look at the repo description and in the README you'll see this code was written by a guy who goes by the handle "Hermit", whose real name is apparently Mihaly Horvath. I published it here for preservation purposes as "Hermit" is notoriously anti-Git (?? ) and likes  to delete his old code. I thought it was interesting enough to make it available to a wider audience. Unfortunately I haven't studied the code in-depth and can't help you with your question.
